import streamlit as st
from utils import *

# Streamlit App
def main():
    # Custom page config
    st.set_page_config(page_title="Image Prompt App", page_icon=":camera:", layout="centered")

    # Hide Streamlit's default footer and menu
    hide_streamlit_style = """
        <style>
        #MainMenu {visibility: hidden;}
        footer {visibility: hidden;}
        .css-164nlkn {visibility: hidden;}
        </style>
    """
    st.markdown(hide_streamlit_style, unsafe_allow_html=True)

    # App title
    st.title("Image Prompt App")
    st.write("Upload an image and enter a prompt to get a response generated by the model.")

    # Upload image
    uploaded_image = st.file_uploader("Choose an image...", type=["png", "jpg", "jpeg"])
    
    # Prompt input
    prompt = st.text_input("Enter your prompt", "Define the image")

    # If the image is uploaded, process and display the result
    if uploaded_image is not None:
        image = Image.open(uploaded_image)
        st.image(image, caption='Uploaded Image', use_column_width=True)
        
        if st.button("Generate Answer"):
            with st.spinner("Processing..."):
                result = process_single_image_and_get_result(image, prompt)
            st.success("Result generated!")
            st.write("**Answer:**", result)

    # Social links
    st.markdown("---")
    st.markdown("**Created by [Umar](https://x.com/Umar26338572)**")
    col1, col2 = st.columns([1, 10])
    with col1:
        st.image("https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/x-social-media-black-icon.png", width=20)
    with col2:
        st.markdown("[Twitter](https://x.com/Umar26338572)")
    
    col1, col2 = st.columns([1, 10])
    with col1:
        st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTO9lOYvVYtruNLntp5K61JoX4mACQZ0BmTqQ&s", width=20)
    with col2:
        st.markdown("[LinkedIn](https://www.linkedin.com/in/umarigan/)")

if __name__ == "__main__":
    main()
